name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub (optional)
      # Uncomment if you need to push to Docker Hub
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image
      - name: Build Docker Image
        run: docker build -t your-image-name:latest .

      # Step 5: Run a container to test the build
      - name: Run and Test Container
        run: |
          docker run -d --name test-container -p 8080:80 your-image-name:latest
          sleep 5
          curl -f http://localhost:8080 || (echo "App failed to start!" && exit 1)

      # Step 6: (Optional) Push Docker image to Docker Hub
      # Uncomment if you need to push the image
      # - name: Push Docker Image
      #   run: docker push your-image-name:latest
